name: Setup cargo-rail Environment
description: |
  Install Rust toolchain, cargo tools, and configure caching.
  All actions skip if already installed.

inputs:
  cache-key:
    description: Additional cache key suffix
    required: false
    default: ""

runs:
  using: composite
  steps:
    # Install cargo tools FIRST, before Rust toolchain installation
    # This prevents Windows issues where massive toolchain updates interfere with cargo bin directory
    - name: Install just
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: just

    - name: Install cargo-nextest
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: cargo-nextest

    - name: Install cargo-deny
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: cargo-deny

    - name: Install cargo-audit
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: cargo-audit

    - name: Install cargo-semver-checks
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: cargo-semver-checks

    - name: Install git-cliff
      uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9  # v2
      with:
        tool: git-cliff

    - name: Install Rust Nightly Toolchain
      uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331  # master
      with:
        toolchain: nightly
        components: clippy, rustfmt

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1  # v2.8.1
      with:
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        # Cache Strategy:
        # - Caches: ~/.cargo (deps, tools) and ./target (build artifacts)
        # - Cache key includes: workflow, platform, rustc version, Cargo.lock hash
        # - Host triple automatically included in cache key
        # - Separate caches per workflow and target triple via 'key' input
        # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

        # Shared prefix: stable across commits (invalidates on bump)
        shared-key: "cargo-rail-v1"

        # Workflow and platform-specific suffix: commit-ubuntu-latest, commit-macos-latest, etc.
        # Ensures each workflow and platform maintains separate cache
        key: ${{ inputs.cache-key }}

        # Cache even on test failures (build artifacts still useful)
        cache-on-failure: true

        # Only save from main branch (prevents cache thrashing)
        # Feature branches READ from main's cache but don't WRITE new ones
        save-if: ${{ github.ref == 'refs/heads/main' }}
