//! Integration tests for `cargo rail init` command

use crate::helpers::{TestWorkspace, load_rail_config, run_cargo_rail};
use anyhow::Result;

#[test]
fn test_init_creates_config() -> Result<()> {
  let ws = TestWorkspace::new_named("init-basic")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init command
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify success
  assert!(output.status.success(), "init should succeed");

  // Verify config was created
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(config_path.exists(), "config file should be created");

  // Verify config is valid TOML and contains expected sections
  let config_content = std::fs::read_to_string(config_path)?;
  assert!(config_content.contains("[workspace]"));
  assert!(config_content.contains("[toolchain]"));
  assert!(config_content.contains("[unify]"));
  assert!(config_content.contains("[policy]"));
  assert!(config_content.contains("[security]"));

  // Verify comprehensive comments
  assert!(config_content.contains("# Generated by: cargo rail init"));
  assert!(config_content.contains("Toolchain Configuration"));
  assert!(config_content.contains("Dependency Unification"));
  assert!(config_content.contains("Workspace Policy"));
  assert!(config_content.contains("Security"));
  assert!(config_content.contains("Split/Sync"));

  Ok(())
}

#[test]
fn test_init_respects_force_flag() -> Result<()> {
  let ws = TestWorkspace::new_named("init-force")?;
  ws.remove_config()?; // Remove default config for init test

  // Create initial config
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(config_path.exists());

  // Try to init again without --force (should fail)
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;
  assert!(!output.status.success(), "init should fail when config exists");
  assert!(
    String::from_utf8_lossy(&output.stderr).contains("already exists"),
    "error should mention config already exists"
  );

  // Try with --force (should succeed)
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--force", "--non-interactive"])?;
  assert!(output.status.success(), "init --force should succeed");

  Ok(())
}

#[test]
fn test_init_detects_toolchain() -> Result<()> {
  let ws = TestWorkspace::new_named("init-toolchain")?;
  ws.remove_config()?; // Remove default config for init test

  // Create rust-toolchain.toml with specific version
  std::fs::write(
    ws.path.join("rust-toolchain.toml"),
    r#"[toolchain]
channel = "1.76.0"
profile = "minimal"
components = ["clippy", "rustfmt"]
"#,
  )?;

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify config detects toolchain
  let config_content = std::fs::read_to_string(ws.path.join(".config/rail.toml"))?;
  assert!(
    config_content.contains("channel = \"1.76.0\""),
    "should detect channel from rust-toolchain.toml"
  );
  assert!(
    config_content.contains("profile = \"minimal\""),
    "should detect profile from rust-toolchain.toml"
  );
  assert!(
    config_content.contains("clippy"),
    "should detect components from rust-toolchain.toml"
  );

  Ok(())
}

#[test]
fn test_init_detects_policy_from_cargo_toml() -> Result<()> {
  let ws = TestWorkspace::new_named("init-policy")?;
  ws.remove_config()?; // Remove default config for init test

  // Update workspace Cargo.toml to add rust-version to existing workspace.package
  let cargo_toml = &ws.path.join("Cargo.toml");
  let existing_content = std::fs::read_to_string(cargo_toml)?;

  // Add rust-version to existing [workspace.package] section
  let new_content = existing_content.replace("edition = \"2021\"", "edition = \"2021\"\nrust-version = \"1.75.0\"");
  std::fs::write(cargo_toml, new_content)?;

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify config detects policy
  let config_content = std::fs::read_to_string(ws.path.join(".config/rail.toml"))?;
  assert!(
    config_content.contains("resolver = \"2\""),
    "should detect resolver from Cargo.toml"
  );
  assert!(
    config_content.contains("edition = \"2021\""),
    "should detect edition from Cargo.toml"
  );
  assert!(
    config_content.contains("msrv = \"1.75.0\""),
    "should detect MSRV from rust-version"
  );

  Ok(())
}

#[test]
fn test_init_dry_run() -> Result<()> {
  let ws = TestWorkspace::new_named("init-dry-run")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init with --dry-run
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--dry-run", "--non-interactive"])?;

  // Verify success
  assert!(output.status.success(), "dry-run should succeed");

  // Verify config was NOT created
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(!config_path.exists(), "config file should NOT be created in dry-run");

  // Verify output shows config
  let stdout = String::from_utf8_lossy(&output.stdout);
  assert!(stdout.contains("--- .config/rail.toml ---"));
  assert!(stdout.contains("[workspace]"));
  assert!(stdout.contains("[toolchain]"));

  Ok(())
}

#[test]
fn test_init_custom_output_path() -> Result<()> {
  let ws = TestWorkspace::new_named("init-custom-path")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init with custom output
  run_cargo_rail(
    &ws.path,
    &["rail", "init", "--non-interactive", "--output", "rail.toml"],
  )?;

  // Verify config was created at custom path
  let config_path = &ws.path.join("rail.toml");
  assert!(config_path.exists(), "config should be created at custom path");

  // Verify default path was NOT created
  let default_path = &ws.path.join(".config/rail.toml");
  assert!(!default_path.exists(), "config should NOT be at default path");

  Ok(())
}

#[test]
fn test_init_creates_directory_if_needed() -> Result<()> {
  let ws = TestWorkspace::new_named("init-mkdir")?;
  ws.remove_config()?; // Remove default config for init test

  // Remove .config directory entirely for this test
  let config_dir = &ws.path.join(".config");
  if config_dir.exists() {
    std::fs::remove_dir_all(config_dir)?;
  }
  assert!(!config_dir.exists(), ".config should not exist initially");

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify .config was created
  assert!(config_dir.exists(), ".config directory should be created");
  assert!(config_dir.is_dir(), ".config should be a directory");

  // Verify config file exists
  assert!(config_dir.join("rail.toml").exists());

  Ok(())
}

#[test]
fn test_init_generated_config_is_valid() -> Result<()> {
  let ws = TestWorkspace::new_named("init-valid")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Try to load the config using RailConfig
  let config = load_rail_config(&ws.path)?;

  // Verify basic fields
  assert_eq!(config.workspace.root.to_str().unwrap(), ".");
  assert_eq!(config.toolchain.channel, "stable");
  assert_eq!(config.toolchain.profile, "default");
  assert!(config.unify.use_all_features);
  assert!(!config.security.require_signed_commits);
  assert_eq!(config.security.protected_branches, vec!["main", "master"]);

  Ok(())
}

#[test]
fn test_init_with_rust_toolchain_plain_file() -> Result<()> {
  let ws = TestWorkspace::new_named("init-toolchain-plain")?;
  ws.remove_config()?; // Remove default config for init test

  // Create plain rust-toolchain file (no .toml extension)
  std::fs::write(ws.path.join("rust-toolchain"), "1.80.0\n")?;

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify config detects channel
  let config_content = std::fs::read_to_string(ws.path.join(".config/rail.toml"))?;
  assert!(
    config_content.contains("channel = \"1.80.0\""),
    "should detect channel from rust-toolchain file"
  );

  Ok(())
}

#[test]
fn test_init_all_fields_present() -> Result<()> {
  let ws = TestWorkspace::new_named("init-all-fields")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  let config_content = std::fs::read_to_string(ws.path.join(".config/rail.toml"))?;

  // Verify ALL config sections and fields are present (active or commented)

  // Workspace
  assert!(config_content.contains("root = \".\""));

  // Toolchain
  assert!(config_content.contains("channel = "));
  assert!(config_content.contains("profile = "));
  assert!(config_content.contains("components = "));
  assert!(config_content.contains("targets = "));

  // Unify
  assert!(config_content.contains("use_all_features = "));
  assert!(config_content.contains("validate_targets = "));
  assert!(config_content.contains("max_parallel_jobs = "));
  assert!(config_content.contains("pin_transitives = "));
  assert!(config_content.contains("pin_hosts = "));

  // Policy - all fields should be present (active or commented)
  assert!(
    config_content.contains("resolver = ") || config_content.contains("# resolver = "),
    "resolver field should be present"
  );
  assert!(
    config_content.contains("msrv = ") || config_content.contains("# msrv = "),
    "msrv field should be present"
  );
  assert!(
    config_content.contains("edition = ") || config_content.contains("# edition = "),
    "edition field should be present"
  );
  assert!(
    config_content.contains("forbid_multiple_versions = "),
    "forbid_multiple_versions should be present"
  );
  assert!(
    config_content.contains("require_workspace_inheritance = "),
    "require_workspace_inheritance should be present"
  );
  assert!(
    config_content.contains("# allowed_licenses = "),
    "allowed_licenses should be commented"
  );
  assert!(
    config_content.contains("# forbid_patch_replace = "),
    "forbid_patch_replace should be commented"
  );

  // Security - all fields should be present (active or commented)
  assert!(
    config_content.contains("# ssh_key_path = "),
    "ssh_key_path should be commented"
  );
  assert!(
    config_content.contains("# signing_key_path = "),
    "signing_key_path should be commented"
  );
  assert!(
    config_content.contains("require_signed_commits = "),
    "require_signed_commits should be present"
  );
  assert!(
    config_content.contains("# pr_branch_pattern = "),
    "pr_branch_pattern should be commented"
  );
  assert!(
    config_content.contains("protected_branches = "),
    "protected_branches should be present"
  );

  // Split/Sync - example should be present
  assert!(config_content.contains("# [[splits]]"));
  assert!(config_content.contains("# name = "));
  assert!(config_content.contains("# remote = "));
  assert!(config_content.contains("# branch = "));
  assert!(config_content.contains("# mode = "));

  Ok(())
}
