//! Integration tests for `cargo rail init` command

use crate::helpers::{TestWorkspace, load_rail_config, run_cargo_rail};
use anyhow::Result;

#[test]
fn test_init_creates_config() -> Result<()> {
  let ws = TestWorkspace::new_named("init-basic")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init command
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify success
  assert!(output.status.success(), "init should succeed");

  // Verify config was created
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(config_path.exists(), "config file should be created");

  // Verify config is valid TOML and contains expected sections
  let config_content = std::fs::read_to_string(config_path)?;
  assert!(config_content.contains("[workspace]"));

  // Verify comprehensive comments
  assert!(config_content.contains("# Generated by: cargo rail init"));

  assert!(config_content.contains("Split/Sync"));

  Ok(())
}

#[test]
fn test_init_respects_force_flag() -> Result<()> {
  let ws = TestWorkspace::new_named("init-force")?;
  ws.remove_config()?; // Remove default config for init test

  // Create initial config
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(config_path.exists());

  // Try to init again without --force (should fail)
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;
  assert!(!output.status.success(), "init should fail when config exists");
  assert!(
    String::from_utf8_lossy(&output.stderr).contains("already exists"),
    "error should mention config already exists"
  );

  // Try with --force (should succeed)
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--force", "--non-interactive"])?;
  assert!(output.status.success(), "init --force should succeed");

  Ok(())
}

#[test]
fn test_init_dry_run() -> Result<()> {
  let ws = TestWorkspace::new_named("init-dry-run")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init with --dry-run
  let output = run_cargo_rail(&ws.path, &["rail", "init", "--dry-run", "--non-interactive"])?;

  // Verify success
  assert!(output.status.success(), "dry-run should succeed");

  // Verify config was NOT created
  let config_path = &ws.path.join(".config/rail.toml");
  assert!(!config_path.exists(), "config file should NOT be created in dry-run");

  // Verify output shows config
  let stdout = String::from_utf8_lossy(&output.stdout);
  assert!(stdout.contains("[workspace]"));
  assert!(stdout.contains("[unify]"));

  Ok(())
}

#[test]
fn test_init_custom_output_path() -> Result<()> {
  let ws = TestWorkspace::new_named("init-custom-path")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init with custom output
  run_cargo_rail(
    &ws.path,
    &["rail", "init", "--non-interactive", "--output", "rail.toml"],
  )?;

  // Verify config was created at custom path
  let config_path = &ws.path.join("rail.toml");
  assert!(config_path.exists(), "config should be created at custom path");

  // Verify default path was NOT created
  let default_path = &ws.path.join(".config/rail.toml");
  assert!(!default_path.exists(), "config should NOT be at default path");

  Ok(())
}

#[test]
fn test_init_creates_directory_if_needed() -> Result<()> {
  let ws = TestWorkspace::new_named("init-mkdir")?;
  ws.remove_config()?; // Remove default config for init test

  // Remove .config directory entirely for this test
  let config_dir = &ws.path.join(".config");
  if config_dir.exists() {
    std::fs::remove_dir_all(config_dir)?;
  }
  assert!(!config_dir.exists(), ".config should not exist initially");

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Verify .config was created
  assert!(config_dir.exists(), ".config directory should be created");
  assert!(config_dir.is_dir(), ".config should be a directory");

  // Verify config file exists
  assert!(config_dir.join("rail.toml").exists());

  Ok(())
}

#[test]
fn test_init_generated_config_is_valid() -> Result<()> {
  let ws = TestWorkspace::new_named("init-valid")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  // Try to load the config using RailConfig
  let config = load_rail_config(&ws.path)?;

  // Verify basic fields
  assert_eq!(config.workspace.root.to_str().unwrap(), ".");

  Ok(())
}

#[test]
fn test_init_all_fields_present() -> Result<()> {
  let ws = TestWorkspace::new_named("init-all-fields")?;
  ws.remove_config()?; // Remove default config for init test

  // Run init
  run_cargo_rail(&ws.path, &["rail", "init", "--non-interactive"])?;

  let config_content = std::fs::read_to_string(ws.path.join(".config/rail.toml"))?;

  // Verify ALL config sections and fields are present (active or commented)

  // Workspace
  assert!(config_content.contains("root = \".\""));

  // Split/Sync - example should be present
  assert!(config_content.contains("# [[splits]]"));
  assert!(config_content.contains("# name = "));
  assert!(config_content.contains("# remote = "));
  assert!(config_content.contains("# branch = "));
  assert!(config_content.contains("# mode = "));

  Ok(())
}
