//! `cargo rail init` - Initialize cargo-rail configuration
//!
//! Auto-detects workspace structure, toolchain settings, and generates
//! a sensible .config/rail.toml with smart defaults.

use crate::config::{RailConfig, UnifyConfig, WorkspaceConfig};
use crate::error::{RailError, RailResult};
use crate::workspace::WorkspaceContext;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

/// Run the init command to bootstrap rail.toml configuration
///
/// # Arguments
/// * `ctx` - Workspace context (already loaded, contains cargo metadata)
/// * `output_path` - Where to write rail.toml (relative to workspace root)
/// * `force` - Overwrite existing config file
/// * `non_interactive` - Skip all prompts, use defaults
/// * `dry_run` - Print config to stdout instead of writing
pub fn run_init(
  ctx: &WorkspaceContext,
  output_path: &str,
  force: bool,
  non_interactive: bool,
  dry_run: bool,
) -> RailResult<()> {
  let workspace_root = ctx.workspace_root();
  let config_path = workspace_root.join(output_path);

  // 1. Check for existing config
  if let Some(existing) = check_existing_config(workspace_root) {
    if !force {
      return Err(RailError::with_help(
        format!(
          "Configuration already exists at: {}\nUse --force to overwrite or --output to specify a different location",
          existing.display()
        ),
        "Example: cargo rail init --force",
      ));
    }
    if !dry_run {
      println!("⚠️  Overwriting existing config at: {}", existing.display());
    }
  }

  // 2. Detection phase
  let mut unify = default_unify_config();

  // Auto-detect targets from all TOML files in workspace (silent detection)
  let detected_targets = detect_targets(workspace_root);
  unify.validation.targets = detected_targets;

  // 3. Interactive confirmation (unless non-interactive or dry-run)
  if !non_interactive && !dry_run {
    print!("\nGenerate rail.toml with these settings? [Y/n]: ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;
    let input = input.trim().to_lowercase();

    if input == "n" || input == "no" {
      println!("Cancelled.");
      return Ok(());
    }
  }

  // 4. Build config
  let config = build_rail_config(workspace_root.to_path_buf(), unify);

  // 6. Serialize with comments
  let toml_content = serialize_config_with_comments(&config)?;

  // 5. Write or print
  if dry_run {
    println!("{}", toml_content);
  } else {
    ensure_output_dir(&config_path)?;
    write_config_file(&config_path, &toml_content)?;

    println!("✅ Created {}", config_path.display());
    println!("\nNext steps:");
    println!("  cargo rail unify --dry-run  # Preview dependency unification");
  }

  Ok(())
}

/// Auto-detect reasonable unify defaults
fn default_unify_config() -> UnifyConfig {
  UnifyConfig::default()
}

/// Detect target triples across all TOML files in workspace
///
/// Uses fuzzy matching against rustc's canonical target list to find targets
/// regardless of where they're defined (rust-toolchain.toml, .cargo/config.toml,
/// Cross.toml, dist-workspace.toml, etc.).
///
/// Returns sorted list of detected targets.
fn detect_targets(workspace_root: &Path) -> Vec<String> {
  // Use the new comprehensive target detection
  crate::targets::detect_targets(workspace_root).unwrap_or_default()
}

fn build_rail_config(_workspace_root: PathBuf, unify: UnifyConfig) -> RailConfig {
  RailConfig {
    workspace: WorkspaceConfig {
      root: PathBuf::from("."),
    },
    unify,
    release: crate::config::ReleaseConfig::default(),
    splits: vec![], // Empty by default - use 'cargo rail split init' to configure
  }
}

/// Serialize RailConfig to TOML string with minimal, clean comments
fn serialize_config_with_comments(config: &RailConfig) -> RailResult<String> {
  let mut output = String::new();

  // Header
  output.push_str("# cargo-rail configuration\n");
  output.push_str("# Generated by: cargo rail init\n");
  output.push_str("# Documentation: https://github.com/loadingalias/cargo-rail\n\n");

  // Workspace
  output.push_str("[workspace]\n");
  output.push_str(&format!("root = \"{}\"\n\n", config.workspace.root.display()));

  // Dependency Unification
  output.push_str("[unify]\n");
  output.push_str(&format!("use_all_features = {}\n", config.unify.use_all_features));
  output.push_str(&format!("allow_renamed = {}\n", config.unify.allow_renamed));

  if !config.unify.exclude.is_empty() {
    output.push_str("exclude = [");
    for (i, dep) in config.unify.exclude.iter().enumerate() {
      if i > 0 {
        output.push_str(", ");
      }
      output.push_str(&format!("\"{}\"", dep));
    }
    output.push_str("]\n");
  } else {
    output.push_str("exclude = []  # Dependencies to skip unification\n");
  }

  if !config.unify.include.is_empty() {
    output.push_str("include = [");
    for (i, dep) in config.unify.include.iter().enumerate() {
      if i > 0 {
        output.push_str(", ");
      }
      output.push_str(&format!("\"{}\"", dep));
    }
    output.push_str("]\n");
  } else {
    output.push_str("include = []  # Dependencies to force unification\n");
  }

  output.push('\n');

  // Conflict handling
  output.push_str("[unify.conflicts]\n");
  output.push_str(&format!(
    "auto_resolve = {}  # Pick highest version automatically\n",
    config.unify.conflicts.auto_resolve
  ));
  output.push_str(&format!(
    "resolution_mode = \"{}\"  # \"permissive\" or \"strict\"\n",
    config.unify.conflicts.resolution_mode
  ));
  output.push_str(&format!(
    "add_markers = {}  # Add # ⚠️ comments to Cargo.toml\n\n",
    config.unify.conflicts.add_markers
  ));

  // Transitive optimization
  output.push_str("[unify.transitives]\n");
  output.push_str(&format!(
    "consolidate_features = {}  # Add fragmented transitive deps to workspace\n",
    config.unify.transitives.consolidate_features
  ));

  // Serialize host_selection
  match &config.unify.transitives.host_selection {
    crate::config::TransitiveFeatureHost::Auto => {
      output.push_str("host_selection = \"auto\"  # \"auto\", \"root\", \"largest\", or [\"crate-name\"]\n\n");
    }
    crate::config::TransitiveFeatureHost::Root => {
      output.push_str("host_selection = \"root\"\n\n");
    }
    crate::config::TransitiveFeatureHost::Largest => {
      output.push_str("host_selection = \"largest\"\n\n");
    }
    crate::config::TransitiveFeatureHost::Explicit(names) => {
      output.push_str("host_selection = [");
      for (i, name) in names.iter().enumerate() {
        if i > 0 {
          output.push_str(", ");
        }
        output.push_str(&format!("\"{}\"", name));
      }
      output.push_str("]\n\n");
    }
  }

  // Validation
  output.push_str("[unify.validation]\n");
  if !config.unify.validation.targets.is_empty() {
    output.push_str("targets = [");
    for (i, target) in config.unify.validation.targets.iter().enumerate() {
      if i > 0 {
        output.push_str(", ");
      }
      output.push_str(&format!("\"{}\"", target));
    }
    output.push_str("]\n");
  } else {
    output.push_str("targets = []  # Platform-specific validation (e.g., [\"x86_64-unknown-linux-gnu\"])\n");
  }
  output.push_str(&format!(
    "max_parallel_jobs = {}  # 0 = auto-detect\n\n",
    config.unify.validation.max_parallel_jobs
  ));

  // Output
  output.push_str("[unify.output]\n");
  output.push_str(&format!(
    "generate_report = {}\n\n",
    config.unify.output.generate_report
  ));

  // Release
  output.push_str("[release]\n");
  output.push_str(&format!("tag_prefix = \"{}\"\n", config.release.tag_prefix));
  output.push_str(&format!(
    "tag_format = \"{}\"  # Variables: {{crate}}, {{version}}\n",
    config.release.tag_format
  ));
  output.push_str(&format!("require_clean = {}\n", config.release.require_clean));
  output.push_str(&format!("publish_delay = {}\n", config.release.publish_delay));
  output.push_str(&format!(
    "create_github_release = {}\n",
    config.release.create_github_release
  ));
  output.push_str(&format!("sign_tags = {}\n", config.release.sign_tags));
  output.push_str(&format!("changelog_path = \"{}\"\n", config.release.changelog_path));
  output.push_str(&format!(
    "skip_changelog_for = {}\n",
    if config.release.skip_changelog_for.is_empty() {
      "[]".to_string()
    } else {
      format!(
        "[{}]",
        config
          .release
          .skip_changelog_for
          .iter()
          .map(|s| format!("\"{}\"", s))
          .collect::<Vec<_>>()
          .join(", ")
      )
    }
  ));
  output.push_str(&format!(
    "require_changelog_entries = {}\n\n",
    config.release.require_changelog_entries
  ));

  // Splits - Don't include in default init
  output.push_str("# Split/Sync: Use 'cargo rail split init <crate>' to configure individual crates\n");
  output.push_str("# [[splits]]\n");
  output.push_str("# name = \"my-crate\"\n");
  output.push_str("# remote = \"git@github.com:org/my-crate.git\"\n");
  output.push_str("# branch = \"main\"\n");
  output.push_str("# mode = \"single\"\n");
  output.push_str("# publish = true\n");
  output.push_str("#\n");
  output.push_str("# [[splits.paths]]\n");
  output.push_str("# crate = \"crates/my-crate\"\n");

  Ok(output)
}

/// Check if config file already exists at any location
fn check_existing_config(workspace_root: &Path) -> Option<PathBuf> {
  crate::config::RailConfig::find_config_path(workspace_root)
}

/// Ensure output directory exists (create if needed)
fn ensure_output_dir(output_path: &Path) -> RailResult<()> {
  if let Some(parent) = output_path.parent()
    && !parent.exists()
  {
    println!("📁 Creating directory: {}", parent.display());
    fs::create_dir_all(parent)
      .map_err(|e| RailError::message(format!("Failed to create directory {}: {}", parent.display(), e)))?;
  }
  Ok(())
}

/// Write config to file with atomic write (write to temp, then rename)
fn write_config_file(config_path: &Path, content: &str) -> RailResult<()> {
  // Use atomic write pattern (write to temp, then rename)
  let temp_path = config_path.with_extension("toml.tmp");

  fs::write(&temp_path, content).map_err(|e| {
    RailError::with_help(
      format!("Failed to write config to {}: {}", temp_path.display(), e),
      "Check file permissions and ensure the directory is writable",
    )
  })?;

  fs::rename(&temp_path, config_path)
    .map_err(|e| RailError::message(format!("Failed to finalize config file: {}", e)))?;

  Ok(())
}

/// Standalone init that doesn't require WorkspaceContext
///
/// This is used when init is called on a directory that may not have
/// a valid Cargo workspace yet (e.g., empty workspace or invalid state).
pub fn run_init_standalone(
  workspace_root: &Path,
  output_path: &str,
  force: bool,
  _non_interactive: bool,
  dry_run: bool,
) -> RailResult<()> {
  let config_path = workspace_root.join(output_path);

  // 1. Check for existing config
  if let Some(existing) = check_existing_config(workspace_root) {
    if !force {
      return Err(RailError::with_help(
        format!(
          "Configuration already exists at: {}\nUse --force to overwrite or --output to specify a different location",
          existing.display()
        ),
        "Example: cargo rail init --force",
      ));
    }
    if !dry_run {
      println!("⚠️  Overwriting existing config at: {}", existing.display());
    }
  }

  // 2. Detection phase - silent target detection
  let detected_targets = detect_targets(workspace_root);

  // 3. Build config
  let config = RailConfig {
    workspace: WorkspaceConfig {
      root: PathBuf::from("."),
    },
    unify: UnifyConfig {
      use_all_features: true,
      allow_renamed: false,
      exclude: vec![],
      include: vec![],
      conflicts: crate::config::UnifyConflictsConfig::default(),
      transitives: crate::config::UnifyTransitivesConfig::default(),
      validation: crate::config::UnifyValidationConfig {
        targets: detected_targets,
        max_parallel_jobs: 0,
      },
      output: crate::config::UnifyOutputConfig::default(),
      backup: crate::config::UnifyBackupConfig::default(),
    },
    release: crate::config::ReleaseConfig::default(),
    splits: vec![],
  };

  // 5. Serialize with comments
  let config_toml = serialize_config_with_comments(&config)?;

  // 4. Output
  if dry_run {
    println!("{}", config_toml);
  } else {
    // Create parent directory if needed
    if let Some(parent) = config_path.parent() {
      fs::create_dir_all(parent).map_err(|e| {
        RailError::with_help(
          format!("Failed to create directory {}: {}", parent.display(), e),
          "Check file permissions",
        )
      })?;
    }

    write_config_file(&config_path, &config_toml)?;
    println!("✅ Created {}", config_path.display());
    println!("\nNext steps:");
    println!("  cargo rail unify --dry-run  # Preview dependency unification");
  }

  Ok(())
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_serialize_config_with_comments() {
    let config = RailConfig {
      workspace: WorkspaceConfig {
        root: PathBuf::from("."),
      },
      unify: UnifyConfig::default(),
      release: crate::config::ReleaseConfig::default(),
      splits: vec![],
    };

    let toml = serialize_config_with_comments(&config).unwrap();

    // Should contain section headers
    assert!(toml.contains("[workspace]"));
    assert!(toml.contains("[unify]"));

    // Should contain helpful comments
    assert!(toml.contains("cargo-rail configuration"));
    assert!(toml.contains("Documentation:"));
  }
}
