repo = "helix-editor/helix"
commit = "24f45746c"
date = "2025-11-30"

[workspace]
members = 13
lock_deps = 327

[unify]
deps_unified = 16
member_edits = 66
transitives_pinned = 0
dead_features_pruned = 4
deps = [
    "smallvec",
    "indoc",
    "termini",
    "chrono",
    "etcetera",
    "crossterm",
    "log",
    "libc",
    "once_cell",
    "anyhow",
    "rustix",
    "serde_json",
    "fern",
    "tokio",
    "url",
    "serde",
]

[config]
special = false
pin_transitives = false # No workspace-hack
msrv = true
detect_unused = true
