repo = "tokio-rs/tokio"
commit = "ab3996a6"
date = "2025-11-30"

[workspace]
members = 10
lock_deps = 214

[unify]
deps_unified = 10
member_edits = 35
transitives_pinned = 0
dead_features_pruned = 24
unused_deps_removed = 1
deps = [
    "bytes",
    "rand",
    "tokio",
    "parking_lot",
    "tracing",
    "slab",
    "tempfile",
    "libc",
    "loom",
    "futures",
]

[config]
special = false
note = "The async runtime"

# Config options used (from rail.toml)
[rail_config]
include_paths = true
include_renamed = false
pin_transitives = false
msrv = true
detect_unused = true
prune_dead_features = true
