repo = "tokio-rs/tokio"
commit = "ab3996a6"
date = "2025-11-30"

[workspace]
members = 10
lock_deps = 214

[unify]
deps_unified = 10
member_edits = 35
transitives_pinned = 0
deps = [
    "bytes",
    "rand",
    "tokio",
    "parking_lot",
    "tracing",
    "slab",
    "tempfile",
    "libc",
    "loom",
    "futures",
]

[config]
special = false
pin_transitives = false # No workspace-hack
msrv = true
detect_unused = true
