[package]
name = "fixture-service-b"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
extended = ["fixture-api/extended"]
parallel = ["dep:rayon"]

[dependencies]
fixture-api.workspace = true
fixture-native.workspace = true
rayon = { workspace = true, optional = true }
regex.workspace = true
