//! High-level TOML document builders

use super::format::{TomlFormatter, TomlValue};
use crate::config::{ReleaseConfig, UnifyConfig};
use crate::error::RailResult;

/// Rail config builder
pub struct RailConfigBuilder {
  formatter: TomlFormatter,
  sections: Vec<String>,
}

impl Default for RailConfigBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      sections: Vec::new(),
    }
  }
}

impl RailConfigBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add header comments
  pub fn header(&mut self) -> &mut Self {
    self.sections.push(
      "# cargo-rail configuration\n# Generated by: cargo rail init\n# Documentation: https://github.com/loadingalias/cargo-rail\n".to_string()
    );
    self
  }

  /// Add workspace section
  pub fn workspace(&mut self, root: &std::path::Path) -> &mut Self {
    let content = format!("root = \"{}\"", root.display());
    self.sections.push(format!("[workspace]\n{}\n", content));
    self
  }

  /// Add unify section
  pub fn unify(&mut self, config: &UnifyConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!("use_all_features = {}\n", config.use_all_features));
    content.push_str(&format!("allow_renamed = {}\n", config.allow_renamed));

    // Exclude
    if config.exclude.is_empty() {
      content.push_str("exclude = []  # Dependencies to skip unification\n");
    } else {
      content.push_str(&format!(
        "exclude = {}\n",
        self.formatter.array_string(&config.exclude, None)
      ));
    }

    // Include
    if config.include.is_empty() {
      content.push_str("include = []  # Dependencies to force unification\n");
    } else {
      content.push_str(&format!(
        "include = {}\n",
        self.formatter.array_string(&config.include, None)
      ));
    }

    self.sections.push(format!("[unify]\n{}\n", content));

    // Subsections
    self.unify_conflicts(config);
    self.unify_transitives(config);
    self.unify_validation(config);
    self.unify_output(config);

    self
  }

  fn unify_conflicts(&mut self, config: &UnifyConfig) {
    let mut content = String::new();
    content.push_str(&format!(
      "auto_resolve = {}  # Pick highest version automatically\n",
      config.conflicts.auto_resolve
    ));
    content.push_str(&format!(
      "resolution_mode = \"{}\"  # \"permissive\" or \"strict\"\n",
      config.conflicts.resolution_mode
    ));
    content.push_str(&format!(
      "add_markers = {}  # Add # ⚠️ comments to Cargo.toml\n",
      config.conflicts.add_markers
    ));

    self.sections.push(format!("[unify.conflicts]\n{}\n", content));
  }

  fn unify_transitives(&mut self, config: &UnifyConfig) {
    let mut content = String::new();
    content.push_str(&format!(
      "consolidate_features = {}  # Add fragmented transitive deps to workspace\n",
      config.transitives.consolidate_features
    ));

    match &config.transitives.host_selection {
      crate::config::TransitiveFeatureHost::Auto => {
        content.push_str("host_selection = \"auto\"  # \"auto\", \"root\", \"largest\", or [\"crate-name\"]\n");
      }
      crate::config::TransitiveFeatureHost::Root => {
        content.push_str("host_selection = \"root\"\n");
      }
      crate::config::TransitiveFeatureHost::Largest => {
        content.push_str("host_selection = \"largest\"\n");
      }
      crate::config::TransitiveFeatureHost::Explicit(names) => {
        content.push_str(&format!(
          "host_selection = {}\n",
          self.formatter.array_string(names, None)
        ));
      }
    }

    self.sections.push(format!("[unify.transitives]\n{}\n", content));
  }

  fn unify_validation(&mut self, config: &UnifyConfig) {
    let mut content = String::new();

    if config.validation.targets.is_empty() {
      content.push_str("targets = []  # Platform-specific validation (e.g., [\"x86_64-unknown-linux-gnu\"])\n");
    } else {
      content.push_str(&format!(
        "targets = {}\n",
        self.formatter.array_targets(&config.validation.targets)
      ));
    }

    content.push_str(&format!(
      "max_parallel_jobs = {}  # 0 = auto-detect\n",
      config.validation.max_parallel_jobs
    ));

    self.sections.push(format!("[unify.validation]\n{}\n", content));
  }

  fn unify_output(&mut self, config: &UnifyConfig) {
    let content = format!("generate_report = {}\n", config.output.generate_report);
    self.sections.push(format!("[unify.output]\n{}\n", content));
  }

  /// Add release section
  pub fn release(&mut self, config: &ReleaseConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!("tag_prefix = \"{}\"\n", config.tag_prefix));
    content.push_str(&format!(
      "tag_format = \"{}\"  # Variables: {{crate}}, {{version}}\n",
      config.tag_format
    ));
    content.push_str(&format!("require_clean = {}\n", config.require_clean));
    content.push_str(&format!("publish_delay = {}\n", config.publish_delay));
    content.push_str(&format!("create_github_release = {}\n", config.create_github_release));
    content.push_str(&format!("sign_tags = {}\n", config.sign_tags));
    content.push_str(&format!("changelog_path = \"{}\"\n", config.changelog_path));

    if config.skip_changelog_for.is_empty() {
      content.push_str("skip_changelog_for = []\n");
    } else {
      content.push_str(&format!(
        "skip_changelog_for = {}\n",
        self.formatter.array_string(&config.skip_changelog_for, None)
      ));
    }

    content.push_str(&format!(
      "require_changelog_entries = {}\n",
      config.require_changelog_entries
    ));

    self.sections.push(format!("[release]\n{}\n", content));
    self
  }

  /// Add splits template
  pub fn splits_template(&mut self) -> &mut Self {
    let content = r#"# Split/Sync: Use 'cargo rail split init <crate>' to configure individual crates
# [[splits]]
# name = "my-crate"
# remote = "git@github.com:org/my-crate.git"
# branch = "main"
# mode = "single"
# publish = true
#
# [[splits.paths]]
# crate = "crates/my-crate"
"#;
    self.sections.push(content.to_string());
    self
  }

  /// Build final TOML string
  pub fn build(&self) -> RailResult<String> {
    Ok(self.sections.join("\n"))
  }
}

/// Cargo.toml workspace dependencies builder
pub struct WorkspaceDepsBuilder {
  formatter: TomlFormatter,
  deps: Vec<(String, String, Option<String>)>, // Name, Value (formatted), Optional comment
}

impl Default for WorkspaceDepsBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      deps: Vec::new(),
    }
  }
}

impl WorkspaceDepsBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add dependency
  pub fn add(&mut self, name: &str, value: &str) -> &mut Self {
    self.deps.push((name.to_string(), value.to_string(), None));
    self
  }

  /// Add dependency with comment
  pub fn add_with_comment(&mut self, name: &str, value: &str, comment: &str) -> &mut Self {
    self
      .deps
      .push((name.to_string(), value.to_string(), Some(comment.to_string())));
    self
  }

  /// Add dependency with inline table
  pub fn add_table(&mut self, name: &str, pairs: &[(String, TomlValue)]) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, None));
    self
  }

  /// Add dependency with inline table and comment
  pub fn add_table_with_comment(&mut self, name: &str, pairs: &[(String, TomlValue)], comment: &str) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, Some(comment.to_string())));
    self
  }

  /// Build [workspace.dependencies] section
  pub fn build(&self) -> RailResult<String> {
    let mut content = String::from("\n[workspace.dependencies]\n");

    // Sort dependencies
    let mut sorted_deps = self.deps.clone();
    sorted_deps.sort_by(|a, b| a.0.cmp(&b.0));

    for (name, value, comment) in sorted_deps {
      if let Some(c) = comment {
        content.push_str(&format!("{} = {}  # {}\n", name, value, c));
      } else {
        content.push_str(&format!("{} = {}\n", name, value));
      }
    }

    Ok(content)
  }
}

/// Member Cargo.toml builder (for converting to workspace inheritance)
pub struct MemberManifestBuilder {
  formatter: TomlFormatter,
}

impl Default for MemberManifestBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
    }
  }
}

impl MemberManifestBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Convert dependency to workspace = true
  pub fn workspace_dep(&self, _name: &str, features: Option<Vec<String>>) -> String {
    if let Some(feats) = features {
      if feats.is_empty() {
        "{ workspace = true }".to_string()
      } else {
        format!(
          "{{ workspace = true, features = {} }}",
          self.formatter.array_features(&feats)
        )
      }
    } else {
      "{ workspace = true }".to_string()
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::RailConfig;

  #[test]
  fn test_rail_config_builder() {
    let mut builder = RailConfigBuilder::new();
    let config = RailConfig {
      workspace: crate::config::WorkspaceConfig {
        root: std::path::PathBuf::from("."),
      },
      unify: UnifyConfig::default(),
      release: ReleaseConfig::default(),
      splits: vec![],
      formatting: crate::config::FormattingConfig::default(),
    };

    let output = builder
      .header()
      .workspace(&config.workspace.root)
      .unify(&config.unify)
      .release(&config.release)
      .splits_template()
      .build()
      .unwrap();

    assert!(output.contains("[workspace]"));
    assert!(output.contains("[unify]"));
    assert!(output.contains("[release]"));
    assert!(output.contains("# [[splits]]"));
  }

  #[test]
  fn test_workspace_deps_builder() {
    let mut builder = WorkspaceDepsBuilder::new();
    builder.add("anyhow", "\"1.0\"");
    builder.add_table(
      "serde",
      &[
        ("version".to_string(), TomlValue::String("1.0".to_string())),
        ("features".to_string(), TomlValue::Array(vec!["derive".to_string()])),
      ],
    );

    let output = builder.build().unwrap();
    assert!(output.contains("anyhow = \"1.0\""));
    assert!(output.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
  }
}
