//! High-level TOML document builders

use super::format::{TomlFormatter, TomlValue};
use crate::config::{ChangeDetectionConfig, ReleaseConfig, UnifyConfig};
use crate::error::RailResult;

/// Rail config builder
pub struct RailConfigBuilder {
  formatter: TomlFormatter,
  sections: Vec<String>,
}

impl Default for RailConfigBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      sections: Vec::new(),
    }
  }
}

impl RailConfigBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add header comments
  pub fn header(&mut self) -> &mut Self {
    self.sections.push(
      r#"# cargo-rail configuration
# Generated by: cargo rail init
# Documentation: https://github.com/loadingalias/cargo-rail/docs/
#
# Commands:
#   cargo rail init           - Generate this config
#   cargo rail affected       - Show crates affected by changes
#   cargo rail test           - Run tests for affected crates
#   cargo rail unify          - Unify workspace dependencies
#   cargo rail split          - Split crate to standalone repo
#   cargo rail sync           - Sync monorepo <-> split repos
#   cargo rail release        - Publish releases
#
# Exit codes: 0 = success, 1 = changes needed (--check), 2 = error
"#
      .to_string(),
    );
    self
  }

  /// Add targets (workspace-wide, top-level field - must be FIRST after header)
  pub fn targets(&mut self, targets: &[String]) -> &mut Self {
    let mut content = String::new();
    if targets.is_empty() {
      content.push_str("# targets = []  # Platform targets for multi-target validation\n");
    } else {
      content.push_str("# Platform targets for multi-target validation\n");
      content.push_str(&format!("targets = {}\n", self.formatter.array_targets(targets)));
    }
    self.sections.push(content);
    self
  }

  /// Add unify section (simplified to 6 essential options)
  pub fn unify(&mut self, config: &UnifyConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!(
      "include_paths = {}  # Handle path dependencies (default: true)\n",
      config.include_paths
    ));

    content.push_str(&format!(
      "include_renamed = {}  # Handle renamed dependencies (package = \"...\") (default: false)\n",
      config.include_renamed
    ));

    content.push_str(&format!(
      "pin_transitives = {}  # Pin transitive-only deps (workspace-hack replacement, enable for hakari users) (default: false)\n",
      config.pin_transitives
    ));

    match &config.transitive_host {
      crate::config::TransitiveFeatureHost::Root => {
        content.push_str("transitive_host = \"root\"  # Where to put pinned transitive dev-deps: \"root\" or path like \"crates/foo\"\n");
      }
      crate::config::TransitiveFeatureHost::Path(path) => {
        content.push_str(&format!(
          "transitive_host = \"{}\"  # Custom path for transitive dev-deps\n",
          path
        ));
      }
    }

    // Exclude (safety hatch)
    if config.exclude.is_empty() {
      content.push_str("exclude = []  # Dependencies to skip unification (safety hatch)\n");
    } else {
      content.push_str(&format!(
        "exclude = {}  # Dependencies to skip unification\n",
        self.formatter.array_string(&config.exclude, None)
      ));
    }

    // Include (safety hatch)
    if config.include.is_empty() {
      content.push_str("include = []  # Dependencies to force unification (safety hatch)\n");
    } else {
      content.push_str(&format!(
        "include = {}  # Dependencies to force unification\n",
        self.formatter.array_string(&config.include, None)
      ));
    }

    // MSRV computation
    content.push_str(&format!(
      "msrv = {}  # Compute and write rust-version to workspace manifest (default: true)\n",
      config.msrv
    ));

    // MSRV source
    let msrv_source_str = match config.msrv_source {
      crate::config::MsrvSource::Deps => "deps",
      crate::config::MsrvSource::Workspace => "workspace",
      crate::config::MsrvSource::Max => "max",
    };
    content.push_str(&format!(
      "msrv_source = \"{}\"  # How to compute MSRV: deps, workspace, max (default: max)\n",
      msrv_source_str
    ));

    // Strict version compatibility
    content.push_str(&format!(
      "strict_version_compat = {}  # Treat version mismatches as errors (default: true)\n",
      config.strict_version_compat
    ));

    // Exact pin handling
    let exact_pin_str = match config.exact_pin_handling {
      crate::config::ExactPinHandling::Skip => "skip",
      crate::config::ExactPinHandling::Preserve => "preserve",
      crate::config::ExactPinHandling::Warn => "warn",
    };
    content.push_str(&format!(
      "exact_pin_handling = \"{}\"  # How to handle =x.y.z pins: skip, preserve, warn (default: warn)\n",
      exact_pin_str
    ));

    // Major version conflict handling
    let major_conflict_str = match config.major_version_conflict {
      crate::config::MajorVersionConflict::Warn => "warn",
      crate::config::MajorVersionConflict::Bump => "bump",
    };
    content.push_str(&format!(
      "major_version_conflict = \"{}\"  # How to handle major version conflicts: warn (skip), bump (force highest) (default: warn)\n",
      major_conflict_str
    ));

    // Unused dependency detection
    content.push_str(&format!(
      "detect_unused = {}  # Detect unused dependencies (default: true)\n",
      config.detect_unused
    ));

    // Remove unused dependencies
    content.push_str(&format!(
      "remove_unused = {}  # Auto-remove unused deps when applying (default: true)\n",
      config.remove_unused
    ));

    // Max backups
    content.push_str(&format!(
      "max_backups = {}  # Number of backup files to keep (default: 3)\n",
      config.max_backups
    ));

    // Prune dead features
    content.push_str(&format!(
      "prune_dead_features = {}  # Remove features never enabled in resolved graph (default: true)\n",
      config.prune_dead_features
    ));

    // Preserve features (glob patterns)
    if config.preserve_features.is_empty() {
      content.push_str("preserve_features = []  # Features to preserve from pruning (glob patterns: \"unstable-*\")\n");
    } else {
      content.push_str(&format!(
        "preserve_features = {}  # Features to preserve from pruning\n",
        self.formatter.array_string(&config.preserve_features, None)
      ));
    }

    // Detect undeclared features
    content.push_str(&format!(
      "detect_undeclared_features = {}  # Detect features borrowed via Cargo unification (default: true)\n",
      config.detect_undeclared_features
    ));

    // Auto-fix undeclared features
    content.push_str(&format!(
      "fix_undeclared_features = {}  # Auto-fix borrowed features by adding them to Cargo.toml (default: true)\n",
      config.fix_undeclared_features
    ));

    // Skip patterns for undeclared features
    if config.skip_undeclared_patterns.is_empty() {
      content.push_str("skip_undeclared_patterns = []  # Features to skip in undeclared detection (glob patterns)\n");
    } else {
      content.push_str(&format!(
        "skip_undeclared_patterns = {}  # Features to skip in undeclared detection\n",
        self.formatter.array_string(&config.skip_undeclared_patterns, None)
      ));
    }

    self.sections.push(format!("[unify]\n{}\n", content));

    self
  }

  /// Add release section
  pub fn release(&mut self, config: &ReleaseConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!(
      "tag_prefix = \"{}\"  # Prefix for all tags (used via {{prefix}} in tag_format)\n",
      config.tag_prefix
    ));
    content.push_str(&format!(
      "tag_format = \"{}\"  # Variables: {{prefix}}, {{crate}}, {{version}}\n",
      config.tag_format
    ));
    content.push_str(&format!("require_clean = {}\n", config.require_clean));
    content.push_str(&format!("publish_delay = {}\n", config.publish_delay));
    content.push_str(&format!("create_github_release = {}\n", config.create_github_release));
    content.push_str(&format!("sign_tags = {}\n", config.sign_tags));
    content.push_str(&format!("changelog_path = \"{}\"\n", config.changelog_path));

    // Changelog relative to
    let changelog_relative_str = match config.changelog_relative_to {
      crate::config::ChangelogRelativeTo::Crate => "crate",
      crate::config::ChangelogRelativeTo::Workspace => "workspace",
    };
    content.push_str(&format!(
      "changelog_relative_to = \"{}\"  # \"crate\" or \"workspace\" (default: crate)\n",
      changelog_relative_str
    ));

    if config.skip_changelog_for.is_empty() {
      content.push_str("skip_changelog_for = []\n");
    } else {
      content.push_str(&format!(
        "skip_changelog_for = {}\n",
        self.formatter.array_string(&config.skip_changelog_for, None)
      ));
    }

    content.push_str(&format!(
      "require_changelog_entries = {}\n",
      config.require_changelog_entries
    ));

    self.sections.push(format!("[release]\n{}\n", content));
    self
  }

  /// Add change-detection section
  pub fn change_detection(&mut self, config: &ChangeDetectionConfig) -> &mut Self {
    let mut content = String::new();

    // Infrastructure patterns
    content.push_str("# Files that trigger full workspace rebuild when changed\n");
    content.push_str(&format!(
      "infrastructure = {}\n",
      self.formatter.array_string(&config.infrastructure, None)
    ));

    // Custom patterns (only if non-empty)
    if !config.custom.is_empty() {
      content.push_str("\n# Custom path categories for change detection\n");
      content.push_str("[change-detection.custom]\n");
      for (category, patterns) in &config.custom {
        content.push_str(&format!(
          "{} = {}\n",
          category,
          self.formatter.array_string(patterns, None)
        ));
      }
    } else {
      content.push_str("# custom = {}  # Custom path categories (e.g., custom.verify = [\"verify/**/*.rs\"])\n");
    }

    self.sections.push(format!("[change-detection]\n{}\n", content));
    self
  }

  /// Add splits template
  pub fn splits_template(&mut self) -> &mut Self {
    let content = r#"# Split/Sync: Use 'cargo rail split init <crate>' to configure individual crates
# Per-crate configuration uses [crates.<name>] sections:
#
# [crates.my-crate.split]
# remote = "git@github.com:org/my-crate.git"
# branch = "main"
# mode = "single"  # "single" or "combined"
# paths = [{ crate = "crates/my-crate" }]
#
# Split modes:
#   single   - One crate per split repo (default)
#   combined - Multiple crates share one split repo
#              Use workspace_mode = "workspace" to mirror monorepo structure
#
# [crates.my-crate.release]
# publish = true
"#;
    self.sections.push(content.to_string());
    self
  }

  /// Build final TOML string
  pub fn build(&self) -> RailResult<String> {
    Ok(self.sections.join("\n"))
  }
}

/// Cargo.toml workspace dependencies builder
pub struct WorkspaceDepsBuilder {
  formatter: TomlFormatter,
  deps: Vec<(String, String, Option<String>)>, // Name, Value (formatted), Optional comment
}

impl Default for WorkspaceDepsBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      deps: Vec::new(),
    }
  }
}

impl WorkspaceDepsBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add dependency
  pub fn add(&mut self, name: &str, value: &str) -> &mut Self {
    self.deps.push((name.to_string(), value.to_string(), None));
    self
  }

  /// Add dependency with comment
  pub fn add_with_comment(&mut self, name: &str, value: &str, comment: &str) -> &mut Self {
    self
      .deps
      .push((name.to_string(), value.to_string(), Some(comment.to_string())));
    self
  }

  /// Add dependency with inline table
  pub fn add_table(&mut self, name: &str, pairs: &[(String, TomlValue)]) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, None));
    self
  }

  /// Add dependency with inline table and comment
  pub fn add_table_with_comment(&mut self, name: &str, pairs: &[(String, TomlValue)], comment: &str) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, Some(comment.to_string())));
    self
  }

  /// Build [workspace.dependencies] section
  pub fn build(&self) -> RailResult<String> {
    let mut content = String::from("\n[workspace.dependencies]\n");

    // Sort dependencies
    let mut sorted_deps = self.deps.clone();
    sorted_deps.sort_by(|a, b| a.0.cmp(&b.0));

    for (name, value, comment) in sorted_deps {
      if let Some(c) = comment {
        content.push_str(&format!("{} = {}  # {}\n", name, value, c));
      } else {
        content.push_str(&format!("{} = {}\n", name, value));
      }
    }

    Ok(content)
  }
}

/// Member Cargo.toml builder (for converting to workspace inheritance)
pub struct MemberManifestBuilder {
  formatter: TomlFormatter,
}

impl Default for MemberManifestBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
    }
  }
}

impl MemberManifestBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Convert dependency to workspace = true
  pub fn workspace_dep(&self, _name: &str, features: Option<Vec<String>>) -> String {
    if let Some(feats) = features {
      if feats.is_empty() {
        "{ workspace = true }".to_string()
      } else {
        format!(
          "{{ workspace = true, features = {} }}",
          self.formatter.array_features(&feats)
        )
      }
    } else {
      "{ workspace = true }".to_string()
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::RailConfig;

  #[test]
  fn test_rail_config_builder() {
    let mut builder = RailConfigBuilder::new();
    let config = RailConfig {
      targets: vec!["x86_64-unknown-linux-gnu".to_string()],
      unify: UnifyConfig::default(),
      release: ReleaseConfig::default(),
      change_detection: crate::config::ChangeDetectionConfig::default(),
      crates: Default::default(),
    };

    let output = builder
      .header()
      .targets(&config.targets)
      .unify(&config.unify)
      .release(&config.release)
      .change_detection(&config.change_detection)
      .splits_template()
      .build()
      .unwrap();

    assert!(output.contains("targets"));
    assert!(output.contains("[unify]"));
    assert!(output.contains("[release]"));
    assert!(output.contains("[change-detection]"));
    assert!(output.contains("# [crates.my-crate.split]"));
  }

  #[test]
  fn test_workspace_deps_builder() {
    let mut builder = WorkspaceDepsBuilder::new();
    builder.add("anyhow", "\"1.0\"");
    builder.add_table(
      "serde",
      &[
        ("version".to_string(), TomlValue::String("1.0".to_string())),
        ("features".to_string(), TomlValue::Array(vec!["derive".to_string()])),
      ],
    );

    let output = builder.build().unwrap();
    assert!(output.contains("anyhow = \"1.0\""));
    assert!(output.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
  }
}
