//! High-level TOML document builders

use super::format::{TomlFormatter, TomlValue};
use crate::config::{ReleaseConfig, UnifyConfig};
use crate::error::RailResult;

/// Rail config builder
pub struct RailConfigBuilder {
  formatter: TomlFormatter,
  sections: Vec<String>,
}

impl Default for RailConfigBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      sections: Vec::new(),
    }
  }
}

impl RailConfigBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add header comments
  pub fn header(&mut self) -> &mut Self {
    self.sections.push(
      "# cargo-rail configuration\n# Generated by: cargo rail init\n# Documentation: https://github.com/loadingalias/cargo-rail\n".to_string()
    );
    self
  }

  /// Add workspace section
  pub fn workspace(&mut self, root: &std::path::Path) -> &mut Self {
    let content = format!("root = \"{}\"", root.display());
    self.sections.push(format!("[workspace]\n{}\n", content));
    self
  }

  /// Add targets (workspace-wide, top-level field)
  pub fn targets(&mut self, targets: &[String]) -> &mut Self {
    let mut content = String::new();
    if targets.is_empty() {
      content.push_str("# targets = []  # Detected platform targets (run 'cargo rail init' to detect)\n");
    } else {
      content.push_str("# Detected platform targets for multi-platform validation\n");
      content.push_str(&format!("targets = {}\n", self.formatter.array_targets(targets)));
    }
    self.sections.push(content);
    self
  }

  /// Add unify section (simplified to 6 essential options)
  pub fn unify(&mut self, config: &UnifyConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!(
      "include_paths = {}  # Handle path dependencies (default: true)\n",
      config.include_paths
    ));

    content.push_str(&format!(
      "include_renamed = {}  # Handle renamed dependencies (package = \"...\") (default: false)\n",
      config.include_renamed
    ));

    content.push_str(&format!(
      "pin_transitives = {}  # Pin transitive-only deps with fragmented features (workspace-hack replacement) (default: true)\n",
      config.pin_transitives
    ));

    match &config.transitive_host {
      crate::config::TransitiveFeatureHost::Root => {
        content.push_str("transitive_host = \"root\"  # Where to put pinned transitive dev-deps: \"root\" or path like \"crates/foo\"\n");
      }
      crate::config::TransitiveFeatureHost::Path(path) => {
        content.push_str(&format!(
          "transitive_host = \"{}\"  # Custom path for transitive dev-deps\n",
          path
        ));
      }
    }

    // Exclude (safety hatch)
    if config.exclude.is_empty() {
      content.push_str("exclude = []  # Dependencies to skip unification (safety hatch)\n");
    } else {
      content.push_str(&format!(
        "exclude = {}  # Dependencies to skip unification\n",
        self.formatter.array_string(&config.exclude, None)
      ));
    }

    // Include (safety hatch)
    if config.include.is_empty() {
      content.push_str("include = []  # Dependencies to force unification (safety hatch)\n");
    } else {
      content.push_str(&format!(
        "include = {}  # Dependencies to force unification\n",
        self.formatter.array_string(&config.include, None)
      ));
    }

    // MSRV computation
    content.push_str(&format!(
      "msrv = {}  # Compute and write rust-version to workspace manifest (default: false)\n",
      config.msrv
    ));

    // Strict version compatibility
    content.push_str(&format!(
      "strict_version_compat = {}  # Treat version mismatches as errors (default: true)\n",
      config.strict_version_compat
    ));

    // Exact pin handling
    let exact_pin_str = match config.exact_pin_handling {
      crate::config::ExactPinHandling::Skip => "skip",
      crate::config::ExactPinHandling::Preserve => "preserve",
      crate::config::ExactPinHandling::Warn => "warn",
    };
    content.push_str(&format!(
      "exact_pin_handling = \"{}\"  # How to handle =x.y.z pins: skip, preserve, warn (default: warn)\n",
      exact_pin_str
    ));

    // Unused dependency detection
    content.push_str(&format!(
      "detect_unused = {}  # Detect unused dependencies (default: false)\n",
      config.detect_unused
    ));

    self.sections.push(format!("[unify]\n{}\n", content));

    self
  }

  /// Add release section
  pub fn release(&mut self, config: &ReleaseConfig) -> &mut Self {
    let mut content = String::new();

    content.push_str(&format!("tag_prefix = \"{}\"\n", config.tag_prefix));
    content.push_str(&format!(
      "tag_format = \"{}\"  # Variables: {{crate}}, {{version}}\n",
      config.tag_format
    ));
    content.push_str(&format!("require_clean = {}\n", config.require_clean));
    content.push_str(&format!("publish_delay = {}\n", config.publish_delay));
    content.push_str(&format!("create_github_release = {}\n", config.create_github_release));
    content.push_str(&format!("sign_tags = {}\n", config.sign_tags));
    content.push_str(&format!("changelog_path = \"{}\"\n", config.changelog_path));

    if config.skip_changelog_for.is_empty() {
      content.push_str("skip_changelog_for = []\n");
    } else {
      content.push_str(&format!(
        "skip_changelog_for = {}\n",
        self.formatter.array_string(&config.skip_changelog_for, None)
      ));
    }

    content.push_str(&format!(
      "require_changelog_entries = {}\n",
      config.require_changelog_entries
    ));

    self.sections.push(format!("[release]\n{}\n", content));
    self
  }

  /// Add splits template
  pub fn splits_template(&mut self) -> &mut Self {
    let content = r#"# Split/Sync: Use 'cargo rail split init <crate>' to configure individual crates
# [[splits]]
# name = "my-crate"
# remote = "git@github.com:org/my-crate.git"
# branch = "main"
# mode = "single"
# publish = true
#
# [[splits.paths]]
# crate = "crates/my-crate"
"#;
    self.sections.push(content.to_string());
    self
  }

  /// Build final TOML string
  pub fn build(&self) -> RailResult<String> {
    Ok(self.sections.join("\n"))
  }
}

/// Cargo.toml workspace dependencies builder
pub struct WorkspaceDepsBuilder {
  formatter: TomlFormatter,
  deps: Vec<(String, String, Option<String>)>, // Name, Value (formatted), Optional comment
}

impl Default for WorkspaceDepsBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
      deps: Vec::new(),
    }
  }
}

impl WorkspaceDepsBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Add dependency
  pub fn add(&mut self, name: &str, value: &str) -> &mut Self {
    self.deps.push((name.to_string(), value.to_string(), None));
    self
  }

  /// Add dependency with comment
  pub fn add_with_comment(&mut self, name: &str, value: &str, comment: &str) -> &mut Self {
    self
      .deps
      .push((name.to_string(), value.to_string(), Some(comment.to_string())));
    self
  }

  /// Add dependency with inline table
  pub fn add_table(&mut self, name: &str, pairs: &[(String, TomlValue)]) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, None));
    self
  }

  /// Add dependency with inline table and comment
  pub fn add_table_with_comment(&mut self, name: &str, pairs: &[(String, TomlValue)], comment: &str) -> &mut Self {
    let value = self.formatter.inline_table(pairs);
    self.deps.push((name.to_string(), value, Some(comment.to_string())));
    self
  }

  /// Build [workspace.dependencies] section
  pub fn build(&self) -> RailResult<String> {
    let mut content = String::from("\n[workspace.dependencies]\n");

    // Sort dependencies
    let mut sorted_deps = self.deps.clone();
    sorted_deps.sort_by(|a, b| a.0.cmp(&b.0));

    for (name, value, comment) in sorted_deps {
      if let Some(c) = comment {
        content.push_str(&format!("{} = {}  # {}\n", name, value, c));
      } else {
        content.push_str(&format!("{} = {}\n", name, value));
      }
    }

    Ok(content)
  }
}

/// Member Cargo.toml builder (for converting to workspace inheritance)
pub struct MemberManifestBuilder {
  formatter: TomlFormatter,
}

impl Default for MemberManifestBuilder {
  fn default() -> Self {
    Self {
      formatter: TomlFormatter::new(),
    }
  }
}

impl MemberManifestBuilder {
  /// Create a new builder
  pub fn new() -> Self {
    Self::default()
  }

  /// Convert dependency to workspace = true
  pub fn workspace_dep(&self, _name: &str, features: Option<Vec<String>>) -> String {
    if let Some(feats) = features {
      if feats.is_empty() {
        "{ workspace = true }".to_string()
      } else {
        format!(
          "{{ workspace = true, features = {} }}",
          self.formatter.array_features(&feats)
        )
      }
    } else {
      "{ workspace = true }".to_string()
    }
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::config::RailConfig;

  #[test]
  fn test_rail_config_builder() {
    let mut builder = RailConfigBuilder::new();
    let config = RailConfig {
      workspace: crate::config::WorkspaceConfig {
        root: std::path::PathBuf::from("."),
      },
      targets: vec!["x86_64-unknown-linux-gnu".to_string()],
      unify: UnifyConfig::default(),
      release: ReleaseConfig::default(),
      change_detection: crate::config::ChangeDetectionConfig::default(),
      crates: Default::default(),
      formatting: crate::config::FormattingConfig::default(),
    };

    let output = builder
      .header()
      .workspace(&config.workspace.root)
      .targets(&config.targets)
      .unify(&config.unify)
      .release(&config.release)
      .splits_template()
      .build()
      .unwrap();

    assert!(output.contains("[workspace]"));
    assert!(output.contains("targets"));
    assert!(output.contains("[unify]"));
    assert!(output.contains("[release]"));
    assert!(output.contains("# [[splits]]"));
  }

  #[test]
  fn test_workspace_deps_builder() {
    let mut builder = WorkspaceDepsBuilder::new();
    builder.add("anyhow", "\"1.0\"");
    builder.add_table(
      "serde",
      &[
        ("version".to_string(), TomlValue::String("1.0".to_string())),
        ("features".to_string(), TomlValue::Array(vec!["derive".to_string()])),
      ],
    );

    let output = builder.build().unwrap();
    assert!(output.contains("anyhow = \"1.0\""));
    assert!(output.contains("serde = { version = \"1.0\", features = [\"derive\"] }"));
  }
}
