[package]
name = "fact-probe"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "../basic.rs"

[dependencies]
same_dependency_v1 = { package = "same-dependency", path = "same-dependency-v1" }
same_dependency_v2 = { package = "same-dependency", path = "same-dependency-v2" }
unused = { path = "unused" }

[workspace]
exclude = ["same-dependency-v1", "same-dependency-v2", "unused"]
