#!/usr/bin/env python3
"""Generate the command reference from the built executables' public help."""
import argparse
import json
import os
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parent.parent
MARKER = '<!-- Generated by just docs; edit CLI help in src/, then regenerate. -->'


def help_tree(binary, arguments=()):
    result = subprocess.run(
        [str(binary), *arguments, '--help'], cwd=ROOT, check=True,
        text=True, capture_output=True,
        env={**os.environ, 'NO_COLOR': '1', 'TERM': 'dumb', 'COLUMNS': '100'},
    )
    help_text = '\n'.join(line.rstrip() for line in result.stdout.splitlines()).rstrip()
    if result.stderr or '\x1b' in help_text or 'Usage: ' not in help_text:
        raise ValueError(f'unexpected help output: {binary.name} {arguments}')
    yield arguments, help_text
    section = False
    for line in help_text.splitlines():
        if line == 'Commands:':
            section = True
        elif section:
            if not line:
                break
            match = re.fullmatch(r'  ([a-z][a-z0-9-]*)\s+.+', line)
            if not match:
                raise ValueError(f'unrecognized command row: {line}')
            name = match[1]
            if name != 'help':
                yield from help_tree(binary, (*arguments, name))


def documents():
    metadata = json.loads(subprocess.check_output(
        ['cargo', 'metadata', '--no-deps', '--format-version', '1', '--locked', '--offline'],
        cwd=ROOT, text=True,
    ))
    directory = Path(metadata['target_directory']) / 'debug'
    suffix = '.exe' if os.name == 'nt' else ''
    pages = {}
    for name in ['cargo-rail', 'cargo-rail-bench']:
        tree = list(help_tree(directory / (name + suffix)))
        groups = {}
        for arguments, output in tree:
            page = arguments[0] if name == 'cargo-rail' and arguments else name
            heading = ' '.join([name, *arguments])
            groups.setdefault(page, []).append((heading, output))
        for page, commands in groups.items():
            text = f'# {commands[0][0]}\n\n{MARKER}\n\n[Command reference](README.md)\n'
            for index, (heading, output) in enumerate(commands):
                if index:
                    text += f'\n## {heading}\n'
                text += f'\n```text\n{output}\n```\n'
            pages[page + '.md'] = text
    links = '\n'.join(f'- [{name[:-3]}]({name})' for name in sorted(pages))
    pages['README.md'] = (
        f'# Command reference\n\n{MARKER}\n\n'
        'This reference contains the public `--help` output of Cargo-Rail and its cache benchmark.\n'
        'Run `just docs` to regenerate it or `just check-docs` to check for drift.\n\n'
        f'{links}\n'
    )
    return pages


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Reject stale or missing generated files')
    args = parser.parse_args()
    expected = documents()
    destination = ROOT / 'docs' / 'commands'
    existing = {p.name: p for p in destination.glob('*.md')}
    stale = [name for name, content in expected.items()
             if name not in existing or existing[name].read_text() != content]
    obsolete = set(existing) - set(expected)
    if args.check:
        if stale or obsolete:
            raise SystemExit('Command reference differs; run just docs: ' + ', '.join(sorted(set(stale) | obsolete)))
        print(f'Command reference is current ({len(expected)} files)')
        return
    for name in set(stale) & set(existing) | obsolete:
        if MARKER not in existing[name].read_text():
            raise SystemExit(f'Refusing to replace an unowned file: {existing[name]}')
    destination.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (destination / name).write_text(expected[name])
    for name in obsolete:
        existing[name].unlink()
    print(f'Generated {len(expected)} command reference files')


if __name__ == '__main__':
    main()
