repo = "BurntSushi/ripgrep"
commit = "cd1f981"
date = "2025-11-30"

[workspace]
members = 10
lock_deps = 61

[unify]
deps_unified = 9
member_edits = 35
transitives_pinned = 5
deps = ["serde", "bstr", "walkdir", "log", "serde_json", "globset", "regex", "termcolor", "memchr"]

[config]
special = false
pin_transitives = false # No workspace-hack
msrv = true
detect_unused = true
note = "10 workspace members, not a single crate!"
